# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13c7ab91110e05a154e0d218f5797765bf4a0c237d46d0cdce1367c788dc0785b32e7b9cd460b14d901f001e7f56a2882f6d63391a1b06b4c9f55114c37829f2

test:
  secret_key_base: ff435280f0c4e616a85301de2d16ee54e692eff4658df88e5959505c9d2e5a87c25a8fb0e656306c7d3dbd593355c42fc6ea8e06ff4fb201ff0804229d862653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
